spring.application.name=backend
# Application name
# Server port
server.port=8000
# JWT secret key
jwt.secret=jQBFLabtYmzYRE+bVY3UTfMpqgP8j4DgG1UOzU8Za/tYSezwnQx1NfmOlX6Nr7PYjbE0eAXPqmr7efqREvdU/A==

# Datasource configuration
#spring.datasource.url=jdbc:mysql://localhost:3306/backend?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#spring.datasource.username=root
#spring.datasource.password="Ch@nu=1N"
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/mydb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=springuser
spring.datasource.password=springpass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true
# JPA / Hibernate
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Optional: avoid lazy-loading issues
spring.jpa.open-in-view=false
api.prefix=/api/v1